# network parameters
NUM_LABELS: 3 # (background, cosmic, neutrino)
N_INITIAL_FILTERS:  8
NETWORK_DEPTH:  5
RESIDUAL_BLOCKS_PER_LAYER: 3
RESIDUAL_BLOCKS_DEEPEST_LAYER: 8
LABEL_NAMES:  ['background', 'cosmic', 'neutrino']
NPLANES: 3
BATCH_NORM: True
SHARE_PLANE_WEIGHTS: true

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 5
SAVE_ITERATION: 500
REPORT_ITERATION: 1
SUMMARY_ITERATION: 10
BALANCE_LOSS:  True
BASE_LEARNING_RATE:  0.003
TRAINING: True
ITERATIONS: 25000
TRAIN_CONFIG:
    FILE: './config_threeplane/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL: 'main_label'

TEST_CONFIG:
    FILE: './config_threeplane/test_io.cfg'
    FILLER: 'TestIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'test_data'
    KEYWORD_LABEL: 'test_label'

# General parameters:
LOGDIR: 'log_sbnd_cosmictagger/3plane/'
RESTORE: False
GPU: 0
