# network parameters
NUM_LABELS: 3 # (background, cosmic, neutrino)
N_INITIAL_FILTERS:  4
NETWORK_DEPTH:  4
RESIDUAL_BLOCKS_PER_LAYER: 3
LABEL_NAMES:  ['background', 'cosmic', 'neutrino']
NPLANES: 3

# training parameters:
N_MINIBATCH: 3
MINIBATCH_SIZE: 4
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 5
BALANCE_LOSS:  True
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 20000
TRAIN_CONFIG:
    FILE: './config_threeplane/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL: 'main_label'

TEST_CONFIG:
    FILE: './config_threeplane/test_io.cfg'
    FILLER: 'TestIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'test_data'
    KEYWORD_LABEL: 'test_label'

# General parameters:
LOGDIR: 'log_sbnd_cosmictagger/3plane_light/'
RESTORE: False
GPU: 0
