# network parameters
NUM_LABELS: 3 # (background, cosmic, neutrino)
N_INITIAL_FILTERS:  24
NETWORK_DEPTH:  4
RESIDUAL_BLOCKS_PER_LAYER: 3
LABEL_NAMES:  ['background', 'cosmic', 'neutrino']

# training parameters:
N_MINIBATCH: 2
MINIBATCH_SIZE: 6
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 5
BALANCE_LOSS:  True
BASE_LEARNING_RATE:  0.001
TRAINING: True
TRAINING_ITERATIONS: 25000
TRAIN_CONFIG:
    FILE: './config/train_io_nue.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA: 'main_data'
    KEYWORD_LABEL: 'main_label'

# TEST_CONFIG:
#     CONFIG: 'config/test_io.cfg'
#     FILLER: 'TrainIO'
#     VERBOSITY: 3


# General parameters:
LOGDIR: 'log_uresnet_five_particle/nue/'
RESTORE: False
GPU: 0
